"""Three marketing creatives for a single listing, laid out to match the
agent's existing Ideal Buyer Blueprint format: a Digital Ad (title/headline/
description with character budgets), a Print Creative (headline/message/CTA
box), and an Email Creative (subject/preview + short bolded-benefit body).
Every line is templated from real data -- never generated by a live model.
See SKILL.md rule 73.

FAIR HOUSING: every line here describes the PROPERTY, never the buyer.
Nothing from buyer_profile.py (archetype, income band, demographics) reaches
this module. _selftest.py asserts no buyer-type or household-type language
appears in any creative. See rule 74.
"""
import re

from buyer_profile import _type_noun

# Character budgets are this report's own, not a specific ad platform's
# published spec -- shown so an agent can see at a glance how much of the
# available space each field is using before pasting it into whatever
# platform they're running.
BUDGETS = {'title': 125, 'headline': 25, 'description': 30}


def _price_line(prop):
    return f"${prop['list_price']:,.0f}" if prop.get('list_price') else 'Price available on request'


def _kw(text, *words):
    t = (text or '').lower()
    return any(w in t for w in words)


def _fit(text, limit):
    """Trim to a character budget on a word boundary, never mid-word."""
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(' ', 1)[0]
    return cut


def _neighborhood(prop):
    return prop.get('neighborhood') or prop.get('city') or 'this area'


def _feature_phrase(prop):
    """One short standout phrase for headlines -- lot, view or a listing
    keyword, in that order, whichever is actually true."""
    desc = prop.get('description') or ''
    if prop.get('lot_sqft') and prop['lot_sqft'] >= 10000:
        return 'Corner Lot' if _kw(desc, 'corner lot') else 'Big Lot'
    if _kw(desc, 'lake'):
        return 'Near the Lake'
    if _kw(desc, 'mountain view', 'mountain views'):
        return 'Mountain Views'
    if _kw(desc, 'trail'):
        return 'Trailside Living'
    if prop.get('hoa_fee') == 0:
        return 'No HOA'
    return _neighborhood(prop)


def digital_ad(prop):
    beds, baths, sqft = prop.get('beds'), prop.get('baths'), prop.get('sqft')
    ptype = _type_noun(prop.get('property_type')).title()
    neigh = _neighborhood(prop)
    bits = []
    if prop.get('hoa_fee') == 0:
        bits.append('No HOA')
    desc = prop.get('description') or ''
    if _kw(desc, 'park', 'lake', 'trail'):
        bits.append('Steps to Park & Trails')
    title = f"{beds}-Bed {ptype} in {neigh}" if beds else f"{ptype} in {neigh}"
    if bits:
        title += ' | ' + ' | '.join(bits)
    title = _fit(title, BUDGETS['title'])

    feat = _feature_phrase(prop)
    full = f"{neigh} {feat}" if feat != neigh else neigh
    if len(full) > BUDGETS['headline'] and ' ' in neigh:
        short = neigh.split()[0]
        full = f"{short} {feat}" if feat != neigh else short
    headline = _fit(full, BUDGETS['headline'])

    desc_bits = []
    if beds:
        desc_bits.append(f'{beds} Beds')
    if prop.get('hoa_fee') == 0:
        desc_bits.append('No HOA')
    if _kw(desc, 'unfinished', 'rough-in', 'rough in'):
        desc_bits.append('Room to Grow')
    elif sqft:
        desc_bits.append(f'{sqft:,} Sq Ft')
    description = _fit(', '.join(desc_bits) or f'{_price_line(prop)}', BUDGETS['description'])

    return {'title': title, 'headline': headline, 'description': description,
           'title_budget': BUDGETS['title'], 'headline_budget': BUDGETS['headline'],
           'description_budget': BUDGETS['description']}


def _print_headline(prop):
    yr = prop.get('year_built')
    from datetime import date
    age = (date.today().year - yr) if yr else None
    desc = prop.get('description') or ''
    if age and age >= 25 and _kw(desc, 'original', 'original-owner', 'original owner'):
        return f'{age} Years of Care. Now It\u2019s Your Turn.'
    if prop.get('lot_sqft') and prop['lot_sqft'] >= 10000:
        return f'Room to Grow in {_neighborhood(prop)}'
    return f'Welcome Home to {_neighborhood(prop)}'


def print_creative(prop):
    desc = prop.get('description') or ''
    facts = []
    if prop.get('beds') and prop.get('baths'):
        facts.append(f"{prop['beds']} bedrooms")
        if _kw(desc, 'main-floor office', 'main floor office'):
            facts[-1] += ', including a main-floor office'
    if _kw(desc, 'vaulted') and _kw(desc, 'fireplace'):
        facts.append('a vaulted family room with a gas fireplace')
    elif _kw(desc, 'fireplace'):
        facts.append('a gas fireplace')
    if prop.get('lot_sqft'):
        facts.append(f"a {prop['lot_sqft'] / 43560:.2f}-acre lot" if prop['lot_sqft'] >= 10000
                     else f"a {prop['lot_sqft']:,} sq ft lot")
    message = f"This home at {prop.get('address_line', 'this address')} in {_neighborhood(prop)} offers "
    message += (', '.join(facts[:-1]) + f', and {facts[-1]}' if len(facts) > 1
               else facts[0] if facts else f"{prop.get('sqft', 0):,} sq ft of living space")
    message += '.'

    loc_bits = []
    if _kw(desc, 'park', 'lake', 'trail'):
        loc_bits.append('the park, lake and trails')
    if _kw(desc, 'rec center', 'recreation center'):
        loc_bits.append('the rec center')
    if _kw(desc, 'us-36', 'us 36'):
        loc_bits.append('US-36')
    loc_line = f"Steps to {loc_bits[0]}." if loc_bits else None
    if len(loc_bits) > 1:
        loc_line = f"Steps to {loc_bits[0]}. Minutes to {', '.join(loc_bits[1:])}."
    if prop.get('hoa_fee') == 0:
        loc_line = (loc_line + ' No HOA.') if loc_line else 'No HOA.'

    return {'headline': _print_headline(prop), 'message': message, 'location_line': loc_line,
           'price_line': f'Offered at {_price_line(prop)}.'}


def _benefit_lines(prop):
    """Short bolded-benefit clauses for the email body -- each included only
    when the underlying fact is true, in a fixed priority order."""
    desc = prop.get('description') or ''
    lines = []
    if prop.get('beds'):
        bit = f"{prop['beds']} bedrooms"
        if _kw(desc, 'main-floor office', 'main floor office'):
            bit += ', including a main-floor office'
        if _kw(desc, 'vaulted') and _kw(desc, 'built-in', 'built ins', 'built-ins'):
            bit += ', plus a vaulted family room with built-ins'
            if _kw(desc, 'fireplace'):
                bit += ' and a gas fireplace'
        lines.append(('Room where it counts', bit + '.'))
    if _kw(desc, 'primary suite', 'primary bedroom') or _kw(desc, 'sitting area'):
        bit = 'sitting area, ' if _kw(desc, 'sitting area') else ''
        bit += 'private bath' if _kw(desc, 'primary bath') else ''
        if _kw(desc, 'walk-in', 'walk in') and _kw(desc, 'closet'):
            bit += (' and dual closets' if bit else 'dual closets')
            if _kw(desc, 'cedar'):
                bit += ', including a walk-in cedar closet'
        if bit:
            lines.append(('A primary suite with space to breathe', bit + '.'))
    if _kw(desc, 'unfinished', 'rough-in', 'rough in'):
        lines.append(('Build your equity', 'the open basement already has rough-in plumbing, '
                      'ready for the finish you want.'))
    out_bits = []
    if _kw(desc, 'mature', 'landscap'):
        out_bits.append('mature landscaping')
    if _kw(desc, 'deck'):
        out_bits.append('a deck')
    if _kw(desc, 'park', 'lake', 'trail'):
        out_bits.append('steps to the park, lake and trails')
    if prop.get('hoa_fee') == 0:
        out_bits.append('no HOA')
    if out_bits:
        joined = '; '.join(out_bits)
        lines.append(('Outside your door', joined[:1].upper() + joined[1:] + '.'))
    if _kw(desc, 'us-36', 'us 36'):
        lines.append(('Easy to get anywhere', 'quick access to US-36 for a Boulder or Denver commute.'))
    return lines[:5]


def email_creative(prop, agent=None):
    desc = prop.get('description') or ''
    subject = f"A {_neighborhood(prop)} home" + (', priced to move' if False else '')
    subject = f"{_feature_phrase(prop)} in {_neighborhood(prop)}" if _feature_phrase(prop) != _neighborhood(prop) \
        else f"New listing in {_neighborhood(prop)}"
    preview = (f"{prop['beds']} beds" if prop.get('beds') else '') \
        + (', no HOA' if prop.get('hoa_fee') == 0 else '') \
        + f" \u2014 {_price_line(prop)}"

    lines = _benefit_lines(prop)
    body = ["Hi [First Name],",
           f"Homes like this rarely come up: {prop.get('address_line', 'this listing')} in "
           f"{_neighborhood(prop)}."]
    for label, text in lines:
        body.append(f"__{label}__ \u2014 {text}")
    body.append(f"Listed at {_price_line(prop)}. Reply to this email or call to set up a private tour.")

    name = (agent or {}).get('name') or '[Agent Name]'
    brokerage = 'Fidelity National Title' if agent else '[Brokerage Name]'
    phone = (agent or {}).get('phone') or '[Phone]'
    body.append(f"\u2014 {name}, {brokerage}" + (f' | {phone}' if agent else ''))

    return {'subject': subject, 'preview': preview, 'body': '\n\n'.join(body)}


def creatives(prop, buyer=None, agent=None):
    """buyer: accepted for call-site compatibility with earlier versions;
    intentionally UNUSED here -- see the Fair Housing note above."""
    d = digital_ad(prop)
    p = print_creative(prop)
    e = email_creative(prop, agent=agent)
    name = (agent or {}).get('name') or '[Agent Name]'
    brokerage = 'Fidelity National Title' if agent else '[Brokerage Name]'
    phone = (agent or {}).get('phone') or '[Phone]'
    p['cta'] = f"Book a private showing \u2014 {name} | {brokerage}" + (f' | {phone}' if agent else ' | [Website]')

    return {
        'digital': d, 'print': p, 'email': e,
        # Back-compat plain-text renderings for any caller still expecting
        # the earlier flat strings (e.g. a future social/caption use).
        'digital_plain': f"{d['title']}\n\n{d['headline']} \u2014 {d['description']}",
        'print_plain': f"{p['headline']}\n\n{p['message']} {p['location_line'] or ''}\n\n{p['price_line']}",
    }
