"""Three marketing creatives for a single listing -- digital, print, and
email -- built the same way marketing.py builds subdivision copy: real
numbers plugged into template sentences, never generated by a live model.
See SKILL.md rule 73.

FAIR HOUSING: every line here describes the PROPERTY, never the buyer. The
buyer archetype (buyer_profile.py) and area demographics (census_api.py) are
agent-facing planning context only and must never be interpolated into ad
copy -- phrases signaling a preferred household type ("ideal for a family",
"perfect for retirees") are what HUD advertising guidance warns against.
_selftest.py asserts this. See rule 74.
"""
from buyer_profile import _type_noun


def _price_line(prop):
    return f"${prop['list_price']:,.0f}" if prop.get('list_price') else "Price available on request"


def _facts_line(prop):
    bits = []
    if prop.get('beds'):
        bits.append(f"{prop['beds']} bed")
    if prop.get('baths'):
        bits.append(f"{prop['baths']} bath")
    if prop.get('sqft'):
        bits.append(f"{prop['sqft']:,} sq ft")
    return ' · '.join(bits)


def creatives(prop, buyer=None):
    """prop: from listing_api.get_property(). buyer: the dict returned by
    buyer_profile.classify_buyer(), optional -- when given, only its first
    PROPERTY-FEATURE reason is used; the archetype label never reaches ad copy.
    """
    addr = prop.get('address_line') or 'This home'
    city = prop.get('city') or ''
    price = _price_line(prop)
    facts = _facts_line(prop)
    ptype = _type_noun(prop.get('property_type'))
    # Only the property-feature reason is used, never the archetype label.
    top_reason = (buyer or {}).get('reasons', [None])[0]

    # ---------------------------------------------------------- digital
    hook = f"New on the market in {city}" if city else "Just listed"
    digital = (
        f"{hook}: {addr}\n\n"
        f"{price} · {facts}\n\n"
        + (f"{top_reason.split(' -- ')[0]}. " if top_reason else '')
        + f"A {ptype} worth a look.\n\nMessage me for the full details and to schedule a showing."
    )

    # ------------------------------------------------------------ print
    print_copy = (
        f"{addr}\n{price}\n\n"
        f"{facts}\n\n"
        + (f"{top_reason}\n\n" if top_reason else '')
        + "Contact me today to schedule a private showing."
    )

    # ------------------------------------------------------------ email
    subject = f"Just listed: {addr}" + (f" — {price}" if prop.get('list_price') else '')
    email_body = (
        f"Hi,\n\n"
        f"Wanted to make sure you saw this one: {addr} in {city}, listed at {price}.\n\n"
        f"{facts}"
        + (f". {top_reason}" if top_reason else '.')
        + "\n\n"
        + "Happy to walk through it with you, or send the full report with comps and financing.\n\n"
        f"Let me know if you'd like to see it."
    )

    return {
        'digital': digital,
        'print': print_copy,
        'email': {'subject': subject, 'body': email_body},
    }
